services:
  x-api:
    image: alpine
    container_name: x-api-test
    command: sleep infinity
    healthcheck:
      test: ["CMD", "echo", "API is healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  x-db:
    image: alpine
    container_name: x-db-test
    command: sleep infinity

  x-auth:
    image: alpine
    container_name: x-auth-test
    command: sleep infinity
